sudo: false
language: ruby
bundler_args: --path vendor/bundle --jobs=3 --retry=3
script: bundle exec rspec
cache: bundler

before_install:
  - gem install bundler
  - bundle config --local without local_development yard guard
rvm:
  # 2.1, not 2.1.0 until fixed https://github.com/travis-ci/travis-ci/issues/2220
  - 2.4
  - 2.5
  - 2.6
  - jruby
matrix:
  fast_finish: true
