version: '{build}'

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26
    - RUBY_VERSION: 26-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install bundler
  - bundle install --path=vendor/bundle --retry=3 --jobs=3

cache:
  - vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec
  - bundle exec ruby -Ilib bin/metric_fu --no-open
